# Generated by Django 2.2.1 on 2019-05-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoponline', '0002_auto_20190526_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='user',
            new_name='usuario',
        ),
    ]
